encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>/', views.wiki_entry, name='wiki_page'),
    path('wiki/', views.querry_entry, name="querry"),
    path("newpage", views.new_page, name="newpage"),
    path("edit", views.edit_page, name="edit"),
    path("save", views.save, name="save"),
    path("random", views.randoom, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown2
from . import util
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from django.urls import reverse
import random


def md_to_html(title):
    try:
        entry = util.get_entry(title)
        if entry is not None:
            mark_d = markdown2.markdown(entry)
            return mark_d
        else:
            return None
    except Exception as e:
        print(f"An error occured: {str(e)}")
        return None 


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def new_page(request):
    if request.method == "GET":
        return render(request, "encyclopedia/newpage.html")
    elif request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")

        if title and content:
            titles_lower = [entry.lower() for entry in util.list_entries()]
            if title.lower() in titles_lower:
                return render(
                    request, "encyclopedia/error.html", {"error": "Page already exists"}
                )
            else:
                util.save_entry(title, content)
                return HttpResponseRedirect(
                    reverse("encyclopedia:wiki_page", args=[title])
                )
        else:
            return render(
                request,
                "encyclopedia/error.html",
                {"error": "Title and content are required"},
            )
    else:
        return render(request, "encyclopedia/newpage.html")


def edit_page(request):
    if request.method == "POST":
        title = request.POST['entry_title']
        filename = f"entries/{title}.md"
        try:
            with open(filename, "r") as f:
                content = f.read()
            return render(
                request,
                "encyclopedia/editpage.html",
                {"content": content, "title": title},
            )
        except FileNotFoundError:
            return render(
                request,
                "encyclopedia/error.html",
                {"error": "Page not found"},
            )
        except Exception as e:
            return render(
                request,
                "encyclopedia/error.html",
                {"error": f"Error reading file: {str(e)}"},
            )
    else:
        return render(
            request, "encyclopedia/error.html", {"error": "Invalid request method"}
        )

def save(request):
    if request.method == "POST":
        title = request.POST["entry_title"]
        content = request.POST.get("content")

        if title and content:
            util.save_entry(title, content)
            return HttpResponseRedirect(
                reverse("encyclopedia:wiki_page", args=[title])
            )
        else:
            return render(
                request,
                "encyclopedia/error.html",
                {"error": "Title and content are required"},
            )

def randoom(request):
    random_page = random.choice(util.list_entries())
    return HttpResponseRedirect(reverse("encyclopedia:wiki_page", args=[random_page]))

def wiki_entry(request,title):
    try:
        response = md_to_html(title)
        if response is None:
            return render(request,"encyclopedia/error.html",{
                "error": "Page doesn't exist"
            })
        else:
            return render(request, "encyclopedia/entry.html",{
                "title" : title.title(),
                "message": response
            })
    except Exception as e:
        print(f"An error occurred: {str(e)}")  
        return render(request, "encyclopedia/error.html", {
            "error": "An error occurred while processing the request"
        })

def exist(title, pages):
    a, res = len(title) - 1, []
    for entry in pages:
        for j in range(len(entry)-a):
            if title[0] == entry[j]:
                if title == entry[j:j+a+1]:
                    res.append(entry)
    return res                


@csrf_exempt
def querry_entry(request):
    try:
        title = request.GET.get('q', '').lower().strip()
        if title:
            pages = [page.lower() for page in util.list_entries()]
            if title in pages:
                response = md_to_html(title)
                return render(request, "encyclopedia/entry.html", {
                    "title": title.title(),
                    "message": response
                })
            elif res := exist(title, pages):
                return render(request, "encyclopedia/search.html",{
                    "entries": res
                })
        return render(request, "encyclopedia/error.html", {
            "error": "Page doesn't exist"
        })
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        return render(request, "encyclopedia/error.html", {
            "error": "An error occurred while processing the request"
        })

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<style>
    .title-input {
        max-width: 500px;
        width: 100%;
        height: 50px;
        font-size: 24px;
    }

    .content-textarea {
        max-width: 800px;
        width: 100%;
        height: 300px;
        font-size: 16px;
    }
</style>

<h1>Edit Page</h1>

<form action="{% url 'encyclopedia:save' %}" method="post">
    {% csrf_token %}
    <br><br>
    <label for="content"><h5>Edit the content of page:</h5></label>
    <br>
        <textarea id="content" name="content" class="content-textarea">{{ content }}</textarea>
    <br><br>
    <input type="submit" value="Save">
    <input type="hidden" name ="entry_title" value="{{title}}">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block css %}
    <style>
        
        .rectangular-button {
            
            color: black;
           
            padding: 5px 15px;
            
            border-radius: 5px;

            border: 2px solid black;
           
            cursor: pointer;
            
            text-align: center;
            
            display: inline-block;
            
            transition: background-color 0.3s ease;
            
            position: fixed;
            top: 20px;
            right: 20px;
        }
    </style>
{% endblock %}

{% block body %}
    <p>{{ message | safe }}</p>
    <form action="{% url 'encyclopedia:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{title}}">
        <input type="submit" value="Edit" class="rectangular-button">

    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error</h1>
    <p>{{ error }}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                {% csrf_token %}
                <form action="{% url 'encyclopedia:querry' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage'  %}" method="get">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}" method="get">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<style>
    .title-input {
        max-width: 500px;
        width: 100%;
        height: 50px;
        font-size: 24px;
    }

    .content-textarea {
        max-width: 800px;
        width: 100%;
        height: 300px;
        font-size: 16px;
    }
</style>

<h1>Create New Page</h1>

<form action="{% url 'encyclopedia:newpage' %}" method="post">
    {% csrf_token %}
    <label for="title">Title:</label>
    <br>
    <textarea id="title" name="title" class="title-input"></textarea>
    <br><br>
    <label for="content">Enter the content for your page:</label>
    <br>
    <textarea id="content" name="content" class="content-textarea"></textarea>
    <br><br>
    <input type="submit" value="Save">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    <h1>Search Result</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}